### ISSUE TITLE
No such file or directory: '../dataset/glue_multinli/dev_matched_easy.tsv'?

### ISSUE THREAD

**Issue by dqxiu** [UKPLab/emnlp2020-debiasing-unknown#3]
hello! 
I'm puzzled by this problem:
No such file or directory: '../dataset/glue_multinli/dev_matched_easy.tsv'
Is there any data missing?
Looking forward to you reply. Thanks!

**Comment by niiiikou** [comment]
@dqxiu Could you solve this problem? I have exactly the same problem.

**Comment by niiiikou** [comment]
You could find it from here and download it https://github.com/UKPLab/acl2020-confidence-regularization/blob/master/README.md
